sonar.projectKey=brianegge_ha-upgrade-advisor
sonar.organization=brianegge

sonar.sources=custom_components
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml

sonar.pullrequest.comment.enabled=false
