sonar.projectKey=brianegge_ha-upgrade-advisor
sonar.organization=brianegge

# HA requires async keyword on setup/unload functions even when not awaiting
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S6993
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.py
